In [56]:
import numpy as np

## Problem 1.
### Write a function so that the columns of the output matrix are powers of the input vector.
### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
#### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [57]:
x = np.array([1,2,3,4])

In [58]:
np.vander(x, N=3, increasing=False)

# N is use for column
# "increasing=False" is used for descending order or increasing left to right

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [59]:
np.vander(x, N=3, increasing=True)

# "increasing=True" is used for ascending  order or increasing right to left

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16]])

In [60]:
np.vander(x)

# if "N is not mention so squre matirx return"

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [61]:
# Other method 

N=3
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)

## Problem 2.
### Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
import numpy as np
K= 3
X = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N= len(X)

def moving_average(x, k, n):
    m= n-k+1
    for i in range(m):
        y =  (1/k)* np.sum(x[i:k+i])
        result = "y{} {} = ({})/{}".format(i+1,round(y,2), '+'.join([str(j) for j in x[i:k+i]]), k)
        print(result)
moving_average(X, K, N)

y1 5.0 = (3+5+7)/3
y2 4.67 = (5+7+2)/3
y3 5.67 = (7+2+8)/3
y4 6.67 = (2+8+10)/3
y5 9.67 = (8+10+11)/3
y6 28.67 = (10+11+65)/3
y7 49.33 = (11+65+72)/3
y8 72.67 = (65+72+81)/3
y9 84.0 = (72+81+99)/3
y10 93.33 = (81+99+100)/3
y11 116.33 = (99+100+150)/3
